### PR TITLE
added dist.method argument to createClusterMST()

### PR DESCRIPTION
**Pull request by kstreet13**
Here's my update with the different distance metrics that take cluster shape into account. One thing that I think would be nice would be some support for soft clustering. Slingshot currently does this by using weighted versions of mean and covariance, but I don't think the MNN-based distance metric would generalize.

### CODE REVIEW

**Comment by LTLA** [comment]
I did some refactoring to make it a bit easier to read and debug, plus tests and fleshing out the docs; have a look.

Regarding the soft clustering: I suppose this could be permitted from the API if, e.g., `clusters=` was a matrix of cluster weights. This will have to be skipped for `dist.method="mnn"` but that's fine. In any case, that's probably a separate PR.

**Comment by kstreet13** [comment]
Yeah, I agree that the soft clustering is a separate matter and the matrix of weights makes sense (that's how I handled it in Slingshot). Otherwise, I think it looks good!

**Comment by LTLA** [comment]
I'm just going to mention that I mentally interpreted the calculation for `scaled_full` as being the expression inside the `exp()` of a MVN; the larger this was, the less likely that the two centroids came from the same distribution, so to speak. 

I don't know you have a more intuitive/formal explanation, but that's just for the sake of my curiosity.

**Comment by kstreet13** [comment]
Yeah, mathematically that's exactly what it is. Intuitively, when I was writing the paper, I thought of it as an adjusted [Mahalanobis distance](https://en.wikipedia.org/wiki/Mahalanobis_distance), where the covariance matrices are summed to account for the shapes of both clusters.

**Comment by kstreet13** [comment]
Oh, I actually just noticed some issues with that. Originally, I assumed that the distances would only over be used for building an MST, so I could skip the final square root and still get the same tree. But if we want a true "distance" that makes sense with the outgroup and your edge confidence scores, we should probably take the square root.

**Comment by LTLA** [comment]
Feel free to make the change.

**Pull request merged**
